apiVersion: v1
kind: Pod
metadata:
  name: app-1
  labels:
    module: backend
    project: expense
    environment: development
  annotations:
    imageregistry: "Specifies the location of the registry where container images are stored"
    buildURL: "Specifies the link to the CI/CD job associated with the deployment"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:9
    ports:
    - containerPort: 80
    env:
      - name: usernmae
        value: kalpananeelapu
      - name: password
        value: "admin123"
    resources:
      requests:
        cpu: 100m
        memory: 68Mi
      limits:
        cpu: 120m
        memory: 100Mi



      
