apiVersion: v1
kind: Pod
metadata:
  name: application-1
  labels:
    module: backend
    project: expense
    environment: development
  annotations:
    imageregistry: "https://hub.docker.com/"
    buildURL: "https://jenkins.joindevops.com/expense/backend/build/67"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:9
    env:
      - name: username1
        value: devops
      - name: password1
        value: "Admin123"
    resources:
      requests:
        cpu: 100m
        memory: 68Mi
      limits:
        cpu: 120m
        memory: 100Mi
    