apiVersion: v1
kind: Pod
metadata:
  name: application-1
  labels:
    module: backend
    project: expense
    environment: development
  annotations:
    imageregistry: "specify the location of the registry where containers stores images"
    buildURL: "specify the ci/cd job link for the deployment"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      containerPort: 80
  - name: almalinux
    image: almalinux:9
    env:
      - name: username1
        value: kalpananeelapu
      - name: password1
        value: "Admin123"
    resources:
      requests:
        cpu: 100m
        memory: 68Mi
      limits:
        cpu: 120m
        memory: 100Mi
    