apiVersion: v1
kind: pod
metadata:
  name: pod-1
  labels:
    project: expense
    environment: development
    module: backend
  annotations:
    imageregistry: "https://hub.docker.com/"
    buildURL: "here it provides links to CI/CD jobs associated with this deployment"
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    env:
    - name: APP_ENV
      value: "production"
    - name: APP_PORT
      value: "8080"
    resources:
      requests:
        cpu: 100m
        memory: 68mi
      limits:
        cpu: 120m
        memory: 100mi