apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: my-app  # This label is important for service discovery
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
