kind: Service
apiVersion: v1
metadata:
  name: my-clusterip-service
spec:
  selector:
    app: my-app  
  ports:
  - name: http
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port